modLoader="javafml"
loaderVersion="[4,)"
license="ISC License (ISCL) Microsoft Public License (Ms-PL)"

[[mods]]
modId="grandiorite"
version="1.0.0"
displayName="Grandiorite"
displayURL="https://mcreator.net"
credits="Created using MCreator"
authors="thepwrtank18"
description="Adds Diorite, Andesite, and Granite tools."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.grandiorite]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.grandiorite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration